spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  shardingsphere:
    mode: # 不配置默认单机
      type: Standalone # 运行模式类型。可选配置：Standalone、Cluster
      repository:
        type: JDBC # 持久化仓库类型
    datasource:
      names: test
      test:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/test
        username: root
        password: zard
    rules:
      sharding:
        tables: # 数据分片规则配置
          customer:
            actual-data-nodes: test.customer
            table-strategy:
              standard:
                sharding-column: customer_id
                sharding-algorithm-name: customer_id
#            key-generate-strategy: # 分布式序列策略
#              column: id
#              key-generator-name: snowflake
#        key-generators:
#          snowflake:
#            type: SNOWFLAKE
        sharding-algorithms:
          customer_id:
            type: CLASS_BASED
            props:
              strategy: standard
              algorithmClassName: com.example.shardingjdbclearn.config.CspShardingAlgorithms
    props:
      sql-show: true